### ISSUE TITLE
Tagging with mutated vowels (umlauts)

### ISSUE THREAD

**Issue by k0sebamse** [rev138/pod_feeder#10]
Hello,

I started today with tagging the articles pod_feeder is posting (with both category-tags and title-tags).

It seems there is a problem when there are umlauts in the title and the categories (if provided) as they are cut off.

Examples: #müllers -> #llers, #münchen -> #nchen, #tätowierte -> #towierte

Here you can find three affected accounts with the respecting RSS feed:
https://diaspora.kosebamse.com/u/spiegel_online_top
http://www.spiegel.de/schlagzeilen/tops/index.rss

https://diaspora.kosebamse.com/u/tagesschau
http://www.tagesschau.de/xml/rss2

https://diaspora.kosebamse.com/u/sueddeutsche
http://rss.sueddeutsche.de/rss/Topthemen (provides catory tags)

If you need any additional information please let me know.

Thank you in advance.

Cheers
Mirco

**Comment by k0sebamse** [comment]
Hi,

any respond possible?

THX

Cheers
Mirco

**Comment by rev138** [comment]
Hello,

Sorry. I've been very busy with other projects. I'll try to look at it soon.

**Comment by k0sebamse** [comment]
Hi,

just a little bump ;-)

Cheers
Mirco

**Comment by rev138** [comment]
I believe this has been resolved in a recent commit. Please confirm.

**Comment by rev138** [comment]
Ok, should be fixed now!

**Comment by k0sebamse** [comment]
Works! THX a lot
