### ISSUE TITLE
"XML::Simple" error

### ISSUE THREAD

**Issue by andersbateva** [rev138/pod_feeder#11]
`mismatched tag at line 13, column 125, byte 274 at /usr/lib/x86_64-linux-gnu/perl5/5.22/XML/Parser.pm line 187.`
`XML::Simple called at ./pod_feeder.pl line 456.`

I installed every "XML::Simple" I found by using "apt search", and still there is some kind of problem with this module. I don't know how to solve!

**Comment by rev138** [comment]
Hi there,

Can you provide the feed url you're trying?

**Comment by andersbateva** [comment]
http://twitter.com/AndersBateva/

**Comment by rev138** [comment]
You need to supply the script with a valid Atom/RSS url. If you want to cross-post from twitter, you can use the pod_tweeter.pl script instead, which is semi-experimental and in its own branch.

**Comment by andersbateva** [comment]
Hm, so [the official Diaspora* wik](https://wiki.diasporafoundation.org/Tools_to_use_with_Diaspora#Import.2Fexport_and_syndication_tools) is wrong! It says pod_feeder can be used to post "RSS/Atom/Twitter feeds to D*"!
