### ISSUE TITLE
some characters does look to be badly-parsed

### ISSUE THREAD

**Issue by trebmuh** [rev138/pod_feeder#16]
Hi, using a French "ç" character with the option ` --auto-tag français` is giving a badly-formed tag when published on diaspora : reading "#franÃais" , and linking to " #franãais".

**Comment by trebmuh** [comment]
@rev138 : any idea what's going wrong with this?

**Comment by rev138** [comment]
It's probably a utf8 encoding issue. Does it only happen to hashtags, or does it also happen in the message body?

**Comment by trebmuh** [comment]
@rev138 : only in hashtags as far as I know.

**Comment by rev138** [comment]
`--body` of course :D

**Comment by rev138** [comment]
Fixed. Please pull and try now.

**Comment by trebmuh** [comment]
I pulled, then added the `--auto-tag français` tag, then published a new post on my blog and the result is the tag is correctly displayed in my diaspora account.
Thanks @rev138 !

PS: the `--body` doesn't seem to be working for my case but I'll open proper issue for that. Closing here now.
