### ISSUE TITLE
Weird error while running the script

### ISSUE THREAD

**Issue by SkyzohKey** [rev138/pod_feeder#17]
Hey guys, thanks for that awesome bot, first !

I've been running the bot (nicely configured for my use) during ~30 minutes and now it tells me the following error:

```
Can't locate object method "is_success" via package "0" (perhaps you forgot to load "0"?) at /usr/bin/pod_feeder.pl line 157
```

Sorry to not being able to help here, I'm not a perl developer, else i would have submited a PR. :x

**Comment by rev138** [comment]
Hi,

Based on the information at hand, I suspect the values you're passing to either --username --password or --pod-url is incorrect. See if you can manually log in to the pod with those values. If not, please post the exact command you're running (password redacted, of course).

**Comment by rev138** [comment]
Closing due to lack of response.
