### ISSUE TITLE
hackernews rss

### ISSUE THREAD

**Issue by jpope777** [rev138/pod_feeder#2]
I am attempting to switch my [hackernews bot](https://pod.jpope.org/people/3f7b5360ad9a0131671600155811f2b8) from feed2diasp.pl to pod_feeder. It seems that pod_feeder is unable to work with the HN rss feed (https://news.ycombinator.com/rss) for some reason. 

In my testing, I am able to get pod_feeder to work with other rss feeds, just not the HN feed.

When attempting to run the pod_feeder script with the HN feed url, I am not getting any output (errors or otherwise) either. Is there a verbose mode hidden in there somewhere?

**Comment by rev138** [comment]
I'll have a look.

**Comment by rev138** [comment]
It appears that the feed items do not have a"guid" field, which is not something the script expected. Try now.

**Comment by jpope777** [comment]
Yep, it works now. Thanks man!
