### ISSUE TITLE
the --body option doesn't work for my case

### ISSUE THREAD

**Issue by trebmuh** [rev138/pod_feeder#23]
Following https://github.com/rev138/pod_feeder/issues/16

I'm using this line (as a cron job) to automatically publish on diaspora from my blog's feed:
`./pod_feeder.pl --feed-id blog-LibraZiK --feed-url https://librazik.tuxfamily.org/dotclear/blog/?feed/atom --pod-url https://framasphere.org/ --username XXXXXXX --password XXXXXXX --no-branding --auto-tag librazik ... zip other auto-tag... --auto-tag français --body`

(with a fresh pulled from master)

But it still does only publish the header. Example: https://framasphere.org/posts/4287321

That said, I didn't try again [the modification suggested here](https://github.com/rev138/pod_feeder/pull/18#issuecomment-285862641) and I'll do so when I'll publish my next blog post to check if it's working with the current pod_feeder.pl code.

**Comment by trebmuh** [comment]
Following up, I've added the line as suggested by @ldidry but it still not display the body. See https://framasphere.org/posts/4359060 .

**Comment by rev138** [comment]
@trebmuh, @ldidry was on the right track, but there was a little bit more to it. Check out the 'issue_23' branch and let me know how it goes.

**Comment by trebmuh** [comment]
I'll on my next blogpost and will let you know.

**Comment by trebmuh** [comment]
It does seem to be working as expected. See https://framasphere.org/posts/4360335 .

Big thanks to you @rev138 and @ldidry , really appreciated!
