### ISSUE TITLE
Problem with two german newsfeeds

### ISSUE THREAD

**Issue by k0sebamse** [rev138/pod_feeder#3]
Hi,

I have two different problems with two german feeds.

The first feed URL is http://www.heise.de/tp/news-atom.xml
When I try to run it I get
`Can't use string ("Die Volksabstimmung setzt ein de"...) as a HASH ref while "strict refs" in use at /kosebamse/tools/pod_feeder.pl line 408.`

If I run the script again I get another string in the brackets but the same error message. All strings are found in the summary of an article.

The second feed I encounter problems is http://www.spiegel.de/schlagzeilen/index.rss
It seems to be an encoding problem. German umlauts in the title look strange e.g. a german Ü becomes UÌ. But the umlauts in the description are strored correctly.

Thank you very much in advance.

Regards
Mirco

**Comment by rev138** [comment]
Thanks for the report. I will try to look into it in the next couple of days.

**Comment by rev138** [comment]
@k0sebamse I think this should fix it. Let me know.

**Comment by rev138** [comment]
@k0sebamse The second issue should also be fixed. Please confirm.

**Comment by k0sebamse** [comment]
Hi,

I can confirm that the first issue is solved, thanks a lot.

Unfortunately the second issue isn't solved. I still get Healines like
'“SuÌddeutsche Zeitung” im Kreml-Feuer: Putins PresseluÌge'
and it should be
'“Süddeutsche Zeitung” im Kreml-Feuer: Putins Presselüge'

The post is here: https://diaspora.kosebamse.com/posts/39057

Thanks a lot for having a look.

Cheers
Mirco

**Comment by rev138** [comment]
Ok, this *should* fix it, but you'll have to re-import the feed into the db, as the strings aren't properly decoded.

You can either nuke the whole db, or selectively delete rows where 'posted = 0' to just get rid of anything that hasn't been posted yet.

**Comment by k0sebamse** [comment]
After nuking the DB everything works like a charm now!

Thanks a lot for your support - both issues are solved!

Cheers
Mirco
