### ISSUE TITLE
Accentuation Pt-BR have not been shown properly

### ISSUE THREAD

**Issue by diasporabrazil** [rev138/pod_feeder#4]
Hi, and thanks in advance for the great pod_feeder, it's awesome!

I've been coping with an accentuation issue on the publishings since my feeds use Brazilian Portuguese and so they make regular use of accents like these ^ ~ `

Because of that the title and the hash tags of the posts are displayed incorrectly. 
Here follows an [example](https://diasporabrazil.org/posts/33e74df0dfc90133b0aa21ce46e8dff2 )  

In the example the right word 'células' is displayed like 'ceÌlulas'
And the right hashtag '#células' is displayed like '#ceì'
My server is already configured to use Pt-BR as standard language.

Any idea about what I can do to have this fixed?
Tks.

**Comment by rev138** [comment]
I will take a look.

**Comment by diasporabrazil** [comment]
Some further information I've noticed maybe can give you a clue:

I have no problem with [this](http://es.sott.net/xml_engine/signs_rss_cat/14-Ciencia-y-Tecnologia ) feed in Spanish.
I also have no problem when I use [this](http://www.altamente.org/feed/ ) feed from Portugal (they use Portuguese Pt-PT) or from Brazil the words on the posts are displayed perfectly.

But when I use [this](http://feeds.feedburner.com/euronews/pt/home/ ) another feed that also has Portuguese texts but probably is not necessarily configured to Pt-PT or Pt-BR (a website European/UK based), the words are displayed incorrectly.
Examples:
Right words: Experimentação | lacrimogênio | Macedônia
Are seen wrong: Expêrimentação | lacrimogénio | Macedónia

Despite of the feed source (except the Spanish feed above) all post titles that have the vowel __í__ found in words like __Índia__ __incrível__ __artifício__ __Síria__ __Líbano__ are been wrongly published like __'i__ (the accent is coming before the vowel).

In your script, is there a way to identify the source language of the feed and make some adjust before fetching the posts?
Is it possible to add some short words in the script like 'how' 'when' 'is' 'of' 'who' 'she' to be ignored on the auto tag generating process? Sorry about that but I'm newbie in Perl.

**Comment by diasporabrazil** [comment]
Hey, I was wrong.
I also have problems when I use [this](http://inovacaotecnologica.com.br/boletim/rss.xml ) feed from Brazil. The accentuation is a bit [messy](https://diasporabrazil.org/u/inovacao ).

**Comment by rev138** [comment]
I just commited a fix for issue #3 that  I believe is probably the same issue as you are experiencing. Can you pull the latest code and test it?

**Comment by diasporabrazil** [comment]
I've pulled and unzipped the new version of pod_feeder.pl file. 
I just kept the same pod_feeder.db file but the script didn't work. 
So I imagined after the change on the script related to Unicode I should delete the existent pod_feeder.db file and let the script to create a fresh and new one but even the DB file was successfully created, the commands below also didn't work.
Here follows the test commands and the error messages I used:

# perl pod_feeder.pl --feed-id EuronewsHome --feed-url http://feeds.feedburner.com/euronews/pt/home/ --pod-url https://diasporabrazil.org --username myusername1 --password mypassword1 --via diasporabrazil.org --auto-tag noticias --auto-tag euronews --auto-tag bot --limit 1

Publishing EuronewsHome	http://feedproxy.google.com/~r/euronews/pt/home/~3/cVFCg1XFQEc
__HTTP::Message content must be bytes at /usr/share/perl5/HTTP/Request/Common.pm line 94__


# perl pod_feeder.pl --feed-id BBCBrasil --feed-url http://www.bbc.com/portuguese/index.xml --pod-url https://diasporabrazil.org --username myusername2 --password mypassword2 --via diasporabrazil.org --auto-tag noticias --auto-tag bbc --auto-tag brasil --auto-tag bot --limit 1

Publishing BBCBrasil	tag:www.bbcbrasil.com,2016-04-12:/portuguese/noticias/2016/04/160412_galeria_surfe_submarino_rb
__HTTP::Message content must be bytes at /usr/share/perl5/HTTP/Request/Common.pm line 94__


The __/usr/share/perl5/HTTP/Request/Common.pm line 94__ has:
$req->content($content);

Am I missing something? Any hint?

**Comment by diasporabrazil** [comment]
Oops, sorry about the markdown misuse.

**Comment by rev138** [comment]
Try now.

**Comment by diasporabrazil** [comment]
Yay, now the script seems to be fetching and posting the titles with correct accentuation. I'll be watching.
Just another question: Which line on the script I should configure to ignore prepositions like 'to' 'from' 'and' 'for' and pronouns like 'I' 'my' 'me' 'they' 'them' 'his' 'hers' when autogenerating hashtags?

**Comment by rev138** [comment]
Line 463 has a list of "stop words"

**Comment by diasporabrazil** [comment]
Thank you for your brilliant script and thank you for your valuable help.
