### ISSUE TITLE
Error fetching feed, 403 Forbidden

### ISSUE THREAD

**Issue by asterismo** [rev138/pod_feeder#5]
On this feed: https://yts.ag/rss

**Comment by asterismo** [comment]
This feed too: http://9gag-rss.com/api/rss/get?code=9GAGHot&format=2

**Comment by diasporabrazil** [comment]
@asterismo have you tried adding __--user-agent Mozilla/5.0__ at the beginning of the command just before __--feed_id__ ?
It works to me on some feeds.

**Comment by asterismo** [comment]
Wow! that fixed a couple of those feeds! thanks! let me check the remaining bots, i have like 4 or 5 that wasnt working, i'll let you know.

**Comment by asterismo** [comment]
The 9gag feed is not working

Publishing 9gag http://9gag.com/gag/a97V2y6
Use of uninitialized value $base_url in concatenation (.) or string at /root/diabots/pod_feeder.pl line 488.
400 URL must be absolute at /root/diabots/pod_feeder.pl line 160.

**Comment by rev138** [comment]
@asterismo That error would seem to indicate you are not passing it the --pod-url parameter. Can you post the exact command you're running?

**Comment by asterismo** [comment]
*/5 * * * * ~/diabots/pod_feeder.pl --user-agent Mozilla/5.0 --feed-id 9gag --feed-url http://9gag-rss.com/api/rss/get?code=9GAGHot&format=2 --pod-url https://diaspora.undernet.uy --username 9gag --password ajg9hgzxs --category-tags --title-tags > /dev/null 2>&1

I think it not parsing well the special characters in the feed URL

**Comment by asterismo** [comment]
This does not cause error, but it does not post anything

*/15 * * * * ~/diabots/pod_feeder.pl --user-agent Mozilla/5.0 --feed-id elpais1 --feed-url http://servicios.elpais.com.uy/formatos/rss/index.asp?seccion=mundo --pod-url https://diaspora.undernet.uy --username elpais --password ajg9hgzxs --category-tags --title-tags > /dev/null 2>&1

**Comment by rev138** [comment]
In the first case, the problem is due to an ampersand (&) in the url. BASH interprets this as something special. Try putting the whole url in quotes.

In the case of the second, it looks like for some reason the XML is in a format the script doesn't understand (RSS has very loose standards). I'll have to play with it a bit.

**Comment by rev138** [comment]
Also, change your password, please :key:

**Comment by rev138** [comment]
The elpais feed should work now.

**Comment by asterismo** [comment]
thanks, i forgot about the password, i'll change them later. thanks for pointing that out.
