### ISSUE TITLE
Krebs on security: wrong links

### ISSUE THREAD

**Issue by k0sebamse** [rev138/pod_feeder#6]
Hello,

I would like to add the RSS feed from Brian Krebs to an account on my pod.

The feed URL is http://krebsonsecurity.com/feed/

Unfortunately the links are not korrekt. When I hover over the link it is shown correctly:
http://krebsonsecurity.com/2016/04/us-cert-to-windows-users-dump-apple-quicktime

But when I click on the link I get here:
http://krebsonsecurity.com%2Ckrebsonsecurity.com/2016/04/us-cert-to-windows-users-dump-apple-quicktime/

Looks like the host is inserted twice, divided by a comma. I tested this with Firefox, IE, Chrome and Chromium under Windows 7.

The account can be found here: https://diaspora.kosebamse.com/u/krebs_on_security

Thank you very much in advance for your help!

Cheers
Mirco

**Comment by rev138** [comment]
This is not a pod_feeder issue. The link in the pod post is correct, but krebsonsecurity.com's webserver is issuing a redirect to that broken link. See below.

`$ curl -Is http://krebsonsecurity.com/2016/04/us-cert-to-windows-users-dump-apple-quicktime
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 19 Apr 2016 17:26:17 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
Location: http://www.krebsonsecurity.com,www.krebsonsecurity.com/2016/04/us-cert-to-windows-users-dump-apple-quicktime/
Cache-Control: max-age=100
Expires: Tue, 19 Apr 2016 17:27:17 GMT
X-Cache-Status: HIT
`
You might want to contact them, if possible.

**Comment by k0sebamse** [comment]
Thanks a lot for taking care about this so fast and providing help.

Cheers
Mirco

**Comment by rev138** [comment]
No worries. I wish it was a pod_feeder problem so I could fix it :)
