### ISSUE TITLE
Feeds not working

### ISSUE THREAD

**Issue by asterismo** [rev138/pod_feeder#7]
I have a couple of feeds that do not work, maybe need some tweak

https://www.debian.org/News/news

https://blog.popcorntime.sh/rss/

**Comment by rev138** [comment]
Try those now. The Popcorn Time one will require spoofing the user agent.

**Comment by asterismo** [comment]
and this one
http://wcatwc.arh.noaa.gov/events/xml/PAAQAtom.xml

**Comment by asterismo** [comment]
the last one is for tsunami alerts from NOAA

**Comment by rev138** [comment]
The format of that one is so specific I would have to have a special function just to accommodate it. I think you're just SOL on this one :)
