### ISSUE TITLE
Special chars in passwords make the login fail

### ISSUE THREAD

**Issue by TwizzyDizzy** [rev138/pod_feeder#8]
Hi folks,

thanks for pod_feeder :) I just encountered an issue with a password of a diaspora account (`Ogohtee$th2Eeme<`) that made the login fail and therefore posting the feed items failed:

    [1.2.3.4] - - [27/Apr/2016:16:16:22 +0200] "GET /users/sign_in HTTP/1.1" 200 - 0.0247
    [1.2.3.4] - - [27/Apr/2016:16:16:22 +0200] "POST /users/sign_in HTTP/1.1" 200 - 0.1298
    [1.2.3.4] - - [27/Apr/2016:16:16:22 +0200] "GET /unauthenticated HTTP/1.1" 302 - 0.0074

Using the account password `testte` (no special chars) it worked.

Can you confirm that?

Cheers
Thomas

**Comment by rev138** [comment]
Can you try putting the password in quotes on the command line?

**Comment by TwizzyDizzy** [comment]
Oh - I forgot to mention: I did quote the password.

**Comment by rev138** [comment]
Looks like you still need to escape the $ (ie \$). That's a BASH issue, not something that can be fixed in the script.

**Comment by TwizzyDizzy** [comment]
Oh well - indeed, how could I not see that :astonished: You are right, of course!

Thanks for taking the time though!

**Comment by rev138** [comment]
No worries :+1:

**Comment by rev138** [comment]
I need to add ~~more~~ some error handling so it doesn't fail silently like this.
